Product:
    type: object
    config:
        resolveField: '@=resolver("productFields", [info, value, args])'
        description: "A mechanical creature in the Star Wars universe."
        fields:
            id:
                type: "String!"
                description: "The id of the product."
            sku:
                type: "String!"
                description: "The sku of the product."
            stock:
                type: "Int"
                description: "Number of products in stock"