Query:
    type: object
    config:
        description: "A mechanical creature in the Star Wars universe."
        fields:
            allProducts:
                type: "[Product]"
                resolve: "@=resolver('allProducts')"
            product:
                type: "Product"
                args:
                    id:
                      type: Int
                resolve: "@=resolver('product',[args['id']])"
Mutation:
    type: object
    config:
        fields:
            IntroduceShip:
                type: IntroduceShipPayload!
                resolve: "@=mutation('create_ship', [args['input']['shipName'], args['input']['factionId']])"
                args:
                    #using input object type is optional, we use it here to be iso with relay mutation example.
                    input:
                        type: IntroduceShipInput!

IntroduceShipPayload:
    type: object
    config:
        fields:
            ship:
                type: "Ship"
            faction:
                type: "Faction"

IntroduceShipInput:
    type: input-object
    config:
        fields:
            shipName:
                type: "String!"
            factionId:
                type: "String!"