ApiBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: ApiBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sku:
            type: string
            length: 255
            unique: true
        stock:
            type: integer
    lifecycleCallbacks: {  }
