version: '3'

services:
    web:
        image: nginx:1.12.2
        ports:
            - "${EXTERNAL_PORT:-80}:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www:ro
        networks:
          - app-network
    php:
        build: docker/php
        volumes:
            - ./app:/var/www/app
            - ./bin:/var/www/bin
            - ./composer.json:/var/www/composer.json
            - ./composer.lock:/var/www/composer.lock
            - ./src:/var/www/src
            - ./tests:/var/www/tests
            - ./vendor:/var/www/vendor
            - ./web:/var/www/web
            - ./var:/var/www/var
            - ./xdebug:/var/www/xdebug
            - .:/var/www/
        env_file:
            - php-variables.env
        networks:
          - app-network
    db:
        # keopx/mysql available tags: latest, 8.0, 5.7, 5.6, 5.5.
        image: mysql:5.7.18
        ports:
          - "3306:3306"
        volumes:
          - ./data:/var/lib/mysql
          ## Custom setup for MySQL
          # - ./config/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=symfony
          - MYSQL_USER=symfony
          - MYSQL_PASSWORD=symfony
        networks:
          - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - "8080:80"
        links:
          - db
        environment:
          - PMA_HOST=db
        networks:
          - app-network
    composer:
        image: composer
        volumes:
            - .:/app
        env_file:
            - php-variables.env
        networks:
          - app-network
    mailcatcher:
        image: tophfr/mailcatcher:latest
        ports:
            - "${EXTERNAL_MAILCATCHER_PORT:-81}:80"
        expose:
            - "25"
        networks:
          - app-network
networks:
  app-network:
    driver: bridge
