api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

overblog_graphql_single_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/single.yaml"
    prefix: /api

